openapi: 3.0.1
info:
  title: ADM_SaveReport
  description: API Definition of ADM_SaveReport
  version: 1.0.0
servers:
- url: http://localhost:8290/ADM_SaveReport
paths:
  /:
    post:
      responses:
        default:
          description: Default response
