openapi: 3.0.1
info:
  title: testeOauth
  description: API Definition of testeOauth
  version: 1.0.0
servers:
- url: http://localhost:8290/test
paths:
  /test:
    get:
      responses:
        default:
          description: Default response
